<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MasterFormulir; // Pastikan Model diimport

class FormulirSeeder extends Seeder
{
    public function run()
    {
        // Data Formulir
        $data = [
            // --- PASTE HASIL RUMUS EXCEL DISINI ---
            ['nama' => 'PERSETUJUAN TINDAKAN KEDOKTERAN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN/PENOLAKAN RUJUK', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN TES RAPID-Ag', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN TES HIV/AIDS', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN TRANFUSI DARAH', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR PERMINTAAN DARAH', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'MONITORING TRANFUSI DARAH', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENOLAKAN TINDAKAN KEDOKTERAN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERMINTAAN PELAYANAN KEROHANIAN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR PERMINTAAN PENDAPAT LAIN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN TINDAKAN MEDIK RUTIN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR TINDAKAN DO NOT RESUSCITATE (DNR)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'SURAT PENOLAKAN RAWAT INAP', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PEMBERIAN INFORMASI PENOLAKAN RESUSITASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENOLAKAN TINDAKAN DAN APS', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN / PENOLAKAN TINDAKAN MEDIS (MATA)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN / PENOLAKAN TINDAKAN MEDIS (MATA) - PHACOEMULSIFICATION', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN / PENOLAKAN TINDAKAN MEDIS (MATA) - PTERGIUM', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM TRANSFER PASIEN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR KONSULTASI', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'CHECKLIST KEAMANAN PEMBEDAHAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'SURGICAL SAFETY CHECKLIST', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENGKAJIAN PRA BEDAH', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'CHECKLIST INSTRUMEN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'TIME OUT', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LAPORAN OPERASI', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN PRA ANASTESI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'MODIFIED EARLY OBSTETRIC WARNING SCORING (KANDUNGAN)', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'EARLY WARNING SCORING SYSTEM (DEWASA)', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PEDIATRIC EARLY WARNING SCORING SYSTEM (ANAK)', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN PEMBERIAN INFORMASI ANASTESI REGIONAL', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN PEMBERIAN INFORMASI ANASTESI GENERAL', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN PEMBERIAN INFORMASI ANESTESI LOKAL', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENOLAKAN TINDAKAN ANASTESI LOKAL', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PEMBERIAN INFORMASI ANALGESIK PASCA ANASTESI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR ANASTESI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM TIMBANG TERIMA PASIEN PEMBEDAHAN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENGKAJIAN PRA SEDASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR SEDASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ANALGESIK PASKA SEDASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR MONITORING TINDAKAN DENGAN ANASTESI LOKAL', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN UMUM', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN AWAL PASIEN RAWAT JALAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN ULANG PASIEN RAWAT JALAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN AWAL MEDIS RAWAT JALAN PASIEN KANDUNGAN (BOLAK-BALIK)', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN DOKTER GINEKOLOGI RAWAT JALAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN AWAL KEPERAWATAN PASIEN RAWAT JALAN DAN GIGI', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM RESUME TINDAKAN ODONTEKTOMI RAWAT JALAN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM RESUME TINDAKAN RAWAT JALAN', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSEETUJUAN TINDAKAN MEDIK', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENJELASAN TINDAKAN MEDIS', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'INSTRUKSI PASKA OPERASI GIGI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PEMERIKSAAN FISIATRIK', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR KLAIM REHAB', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBARASSESMENT RAWAT JALAN LAYANAN KEDOKTERAN FISIK DAN REHABILITASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR PROTOKOL TERAPI LAYANAN KEDOKTERAN FISIK DAN REHABILITASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'POTRET LEMBAR PROTOKOL TERAPI LAYANAN KEDOKTERAN FISIK DAN REHABILITASI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN AWAL KLIKNIK NYERI', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PROFIL RINGKAS MEDIS RAWAT JALAN (PRMRJ)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN AWAL MEDIS RAWAT JALAN PASIEN MATA', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'INSTALASI GAWAT DARURAT', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'OBSERVASI PASIEN IGD', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN UMUM RAWAT INAP', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERSETUJUAN TINDAKAN MEDIK', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'RINGKASAN RIWAYAT MASUK DAN KELUAR RS', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR EDUKASI PASIEN DAN KELUARGA (BOLAK-BALIK)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN ANAK', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASSESMEN AWAL KEPERAWATAN PASIEN RAWAT INAP', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PERENCANAAN ASUHAN KEPERAWATAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENGKAJIAN ANC/KESEHATAN REPRODUKSI', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN AWAL MEDIS KEBIDANAN DAN KANDUNGAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN AWAL KEPERAWATAN NEONATOLOGI', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN AWAL KEPERAWATAN RAWAT INAP GERIATRI', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'OBSERVASI INPARTU', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'IDENTITAS BAYI BARU LAHIR', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'ASESMEN AWAL MEDIS RAWAT INAP', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'DATA PARTUS', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR PERSALINAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'RENCANA PEMULANGAN PASIEN (BOLAK-BALIK)', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PARTOGRAF', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'CATATAN PERKEMBANGAN PASIEN TERINTEGRASI (CPPT) BOLAK-BALIK', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR SERAH TERIMA ANTAR SHIFT JAGA ( HAND OVER)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'INTENSIVE CARE UNIT (ICU)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR KRITERIA MASUK ICU', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR KRITERIA KELUAR ICU', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LAPORAN PEMASANGAN VENTILATOR', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR CATATAN TINDAKAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LAPORAN  TINDAKAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'OBSERVASI TANDA-TANDA VITAL', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'OBSERVASI CAIRAN', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'PENGELOLAAN OBAT-OBATAN (CPO)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORMULIR REKONSILIASI OBAT', 'kategori' => 'ELEKTRONIK', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'RESUME MEDIS ( RINGKASAN PULANG)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'SKRINING PASIEN MANAJER PELAYANAN PASIEN (MPP)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM A MANAJEMEN PELAYANAN PASIEN (MPP)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM B MANAJER PELAYANAN PASIEN (MPP)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'LEMBAR PERSETUJUAN TINDAKAN MEDIK KB (INFORMED CONSENT)', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
['nama' => 'FORM KARTU PESERTA KB', 'kategori' => 'MANUAL', 'created_at' => now(), 'updated_at' => now()],
            // ... Paste sisanya sampai 50 data ...
        ];

        // Masukkan ke Database
        MasterFormulir::insert($data);
    }
}